// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApvgFPjUpmifx8Lmp_TE3-OtYCNouijNM',
    appId: '1:846677742738:web:6145f177b8fadfd107c24b',
    messagingSenderId: '846677742738',
    projectId: 'chuyung-notes',
    authDomain: 'chuyung-notes.firebaseapp.com',
    storageBucket: 'chuyung-notes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBETzDSxIE2fYjSC42IxPpqQS2XyOVVCYk',
    appId: '1:846677742738:android:4eec3a8c83e69f8407c24b',
    messagingSenderId: '846677742738',
    projectId: 'chuyung-notes',
    storageBucket: 'chuyung-notes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0AgqFLOcSMbl7a_MHc2gAAiL5EXzNd88',
    appId: '1:846677742738:ios:cb35b8b12365a26307c24b',
    messagingSenderId: '846677742738',
    projectId: 'chuyung-notes',
    storageBucket: 'chuyung-notes.appspot.com',
    iosBundleId: 'com.example.flutNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0AgqFLOcSMbl7a_MHc2gAAiL5EXzNd88',
    appId: '1:846677742738:ios:29b1263f85bf6ea307c24b',
    messagingSenderId: '846677742738',
    projectId: 'chuyung-notes',
    storageBucket: 'chuyung-notes.appspot.com',
    iosBundleId: 'com.example.flutNotes.RunnerTests',
  );
}
